version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: arbitrage
      POSTGRES_PASSWORD: arbitrage
      POSTGRES_DB: arbitrage
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  analytics-service:
    build:
      context: ./analytics-service
    environment:
      ANALYTICS_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      NODE_ENV: development
      ANALYTICS_URL: http://analytics-service:8081
      ANALYTICS_TIMEOUT_MS: 8000
    ports:
      - "3000:3000"
    depends_on:
      - analytics-service
      - redis
      - postgres
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres-data:
