server:
  port: ${ANALYTICS_PORT:8081}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      probes:
        enabled: true
